# Generated by Django 3.2 on 2022-06-02 02:46

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('nick_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, help_text='可能是其他平台的头像', null=True, verbose_name='用户头像')),
                ('tel', models.CharField(blank=True, max_length=12, null=True, verbose_name='手机号')),
                ('score', models.FloatField(default=0, verbose_name='用户能力')),
                ('a_unique_id', models.CharField(blank=True, help_text='其他平台的唯一登录id', max_length=64, null=True, verbose_name='id')),
                ('sign_status', models.IntegerField(choices=[(0, '用户名注册'), (1, 'QQ注册'), (2, 'gitee注册'), (3, '手机号注册'), (4, '邮箱注册')], default=0, verbose_name='注册方式')),
                ('account_status', models.IntegerField(choices=[(0, '账号正常'), (1, '账号异常'), (2, '账号被封禁')], default=0, verbose_name='账号状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='知识点名称')),
                ('img_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='知识点图片路径')),
            ],
            options={
                'verbose_name_plural': '知识点',
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=128, null=True, verbose_name='题目类别')),
                ('id', models.CharField(blank=True, max_length=128, null=True, verbose_name='题目编号')),
                ('difficulty', models.FloatField(blank=True, null=True, verbose_name='题目难度')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='题目创建时间')),
                ('origin', models.CharField(blank=True, max_length=128, null=True, verbose_name='题目来源')),
                ('pass_count', models.IntegerField(default=0, verbose_name='题目通过次数')),
                ('submit_count', models.IntegerField(default=0, verbose_name='题目提交次数')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='题目标题')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='题目描述')),
                ('input', models.TextField(blank=True, null=True, verbose_name='题目输入描述')),
                ('output', models.TextField(blank=True, null=True, verbose_name='题目输出描述')),
                ('input_sample', models.TextField(blank=True, null=True, verbose_name='题目输入样例')),
                ('output_sample', models.TextField(blank=True, null=True, verbose_name='题目输出样例')),
                ('html_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='题目对应html路径')),
                ('img_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='题目图片路径')),
            ],
            options={
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='Users2Knowledge',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True, verbose_name='掌握情况')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.problems', verbose_name='知识点号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '题目知识点表',
            },
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='测验时间')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='测验得分')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='测验评价')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '测验记录表',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='报告生成时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='报告文字信息')),
                ('data', models.TextField(blank=True, null=True, verbose_name='生成报告图所用数据字典格式')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '报告表',
            },
        ),
        migrations.CreateModel(
            name='ProblemsTest',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(blank=True, choices=[(1, '提高'), (2, '补弱')], null=True, verbose_name='题目类型')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.problems', verbose_name='题号')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '测试题目表',
            },
        ),
        migrations.CreateModel(
            name='ProblemsRecommendation',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(blank=True, choices=[(1, '提高'), (2, '补弱')], null=True, verbose_name='题目类型')),
                ('img_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='推荐题目图片路径')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.problems', verbose_name='题号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '推荐题目表',
            },
        ),
        migrations.CreateModel(
            name='Problems2Knowledge',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.knowledge', verbose_name='知识点号')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.problems', verbose_name='题号')),
            ],
            options={
                'verbose_name_plural': '题目知识点表',
            },
        ),
        migrations.CreateModel(
            name='ProblemRecords',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('code_path', models.CharField(blank=True, max_length=128, null=True, verbose_name='题目上传代码路径')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='做题时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.problems', verbose_name='题号')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.testrecord', verbose_name='测验表号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='做题用户')),
            ],
            options={
                'verbose_name_plural': '做题记录',
            },
        ),
    ]
