# Generated by Django 3.2 on 2022-06-08 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users2Concepts',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('current_score', models.FloatField(default=0.0, verbose_name='当前掌握情况')),
                ('last_score', models.FloatField(default=0.0, verbose_name='上一次掌握情况')),
            ],
            options={
                'verbose_name_plural': '题目知识点表',
            },
        ),
        migrations.RenameModel(
            old_name='Problems2Knowledge',
            new_name='Problems2Concepts',
        ),
        migrations.RenameField(
            model_name='problems2concepts',
            old_name='knowledge',
            new_name='concept',
        ),
        migrations.AddField(
            model_name='problemrecords',
            name='prob_submit_count',
            field=models.IntegerField(default=0, verbose_name='当前用户提交这道题目次数'),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='prob_count',
            field=models.IntegerField(default=0, verbose_name='用户本次测验提交题目数'),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='prob_pass_count',
            field=models.IntegerField(default=0, verbose_name='用户本次测验通过题目数'),
        ),
        migrations.RenameModel(
            old_name='Knowledge',
            new_name='Concepts',
        ),
        migrations.DeleteModel(
            name='Users2Knowledge',
        ),
        migrations.AddField(
            model_name='users2concepts',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.concepts', verbose_name='知识点号'),
        ),
        migrations.AddField(
            model_name='users2concepts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
