# Generated by Django 3.2 on 2022-06-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220608_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(0, '简单'), (1, '中等'), (2, '提高')], null=True, verbose_name='题目难度'),
        ),
    ]
