# Generated by Django 3.1.1 on 2022-06-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_problems_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='users2concepts',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='某次知识点掌握情况时间'),
        ),
    ]
