# Generated by Django 3.1.1 on 2022-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_users2concepts_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='users2concepts',
            name='create_date',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='测验时间'),
        ),
        migrations.AddField(
            model_name='users2concepts',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='某次知识点掌握情况时间'),
        ),
    ]
