# Generated by Django 3.1.1 on 2022-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20220609_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepts',
            name='id',
            field=models.IntegerField(blank=True, null=True, verbose_name='知识点在csv中的id'),
        ),
    ]
