# Generated by Django 3.1.1 on 2022-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_concepts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='max_concept_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户掌握最好知识点id'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='min_concept_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户掌握最差知识点id'),
        ),
    ]
