# Generated by Django 3.1.1 on 2022-06-10 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20220610_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('test_date', models.DateTimeField(blank=True, null=True, verbose_name='测试报告生成时间')),
                ('last_test_pass_rate', models.FloatField(default=0.0, verbose_name='上一次测验正确率')),
                ('current_test_pass_rate', models.FloatField(default=0.0, verbose_name='当前测验正确率')),
                ('current_test_prob_count', models.IntegerField(default=0, verbose_name='当前测验题目数')),
                ('current_max_submit_prob_record_id', models.IntegerField(blank=True, null=True, verbose_name='本次测验提交次数最多题目记录nid')),
                ('current_min_submit_prob_record_id', models.IntegerField(blank=True, null=True, verbose_name='本次测验提交次数最少题目记录nid')),
                ('last_max_concept_id', models.IntegerField(blank=True, null=True, verbose_name='上一次测验用户掌握最好知识点id')),
                ('last_min_concept_id', models.IntegerField(blank=True, null=True, verbose_name='上一次测验用户掌握最差知识点id')),
                ('current_max_concept_id', models.IntegerField(blank=True, null=True, verbose_name='这一次测验用户掌握最好知识点id')),
                ('current_min_concept_id', models.IntegerField(blank=True, null=True, verbose_name='这一次测验用户掌握最差知识点id')),
                ('description', models.TextField(blank=True, null=True, verbose_name='报告文字信息')),
                ('data', models.TextField(blank=True, null=True, verbose_name='生成报告图所用数据字典格式')),
                ('test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.testrecord', verbose_name='测试记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '测试报告表',
            },
        ),
    ]
