# Generated by Django 3.1.1 on 2022-06-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_testreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='current_test_pass_rate',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='current_test_prob_count',
        ),
    ]
