# Generated by Django 3.1.1 on 2022-06-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20220610_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testreport',
            old_name='test_record',
            new_name='test',
        ),
    ]
