# Generated by Django 3.1.1 on 2022-06-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20220610_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='current_max_concept_id',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='current_max_submit_prob_record_id',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='current_min_concept_id',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='current_min_submit_prob_record_id',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='last_max_concept_id',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='last_min_concept_id',
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_max_concept',
            field=models.IntegerField(blank=True, null=True, verbose_name='这一次测验用户提升知识点name'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_max_submit_prob',
            field=models.IntegerField(blank=True, null=True, verbose_name='本次测验提交次数最多题目title'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_max_submit_prob_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='本次测验提交次数最多题目次数'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_min_concept',
            field=models.IntegerField(blank=True, null=True, verbose_name='这一次测验用户下降知识点name'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_min_submit_prob',
            field=models.IntegerField(blank=True, null=True, verbose_name='本次测验提交次数最少题目title'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_min_submit_prob_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='本次测验提交次数最少题目次数'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='last_max_concept',
            field=models.IntegerField(blank=True, null=True, verbose_name='上一次测验用户掌握最好知识点name'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='last_min_concept',
            field=models.IntegerField(blank=True, null=True, verbose_name='上一次测验用户掌握最差知识点name'),
        ),
    ]
