# Generated by Django 3.1.1 on 2022-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20220610_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='current_max_concept',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='current_min_concept',
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_max_drop_concept',
            field=models.IntegerField(blank=True, null=True, verbose_name='这一次测验用户下降最多知识点name'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_max_improve_concept',
            field=models.IntegerField(blank=True, null=True, verbose_name='这一次测验用户提升最大知识点name'),
        ),
    ]
