# Generated by Django 3.1.1 on 2022-06-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20220610_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='current_max_drop_concept',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='current_max_improve_concept',
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_drop_concept',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='这一次测验用户下降知识点name'),
        ),
        migrations.AddField(
            model_name='testreport',
            name='current_improve_concept',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='这一次测验用户提升知识点name'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='current_max_submit_prob',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='本次测验提交次数最多题目title'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='current_min_submit_prob',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='本次测验提交次数最少题目title'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='last_max_concept',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='上一次测验用户掌握最好知识点name'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='last_min_concept',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='上一次测验用户掌握最差知识点name'),
        ),
    ]
