# Generated by Django 3.1.1 on 2022-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_problemstest_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemstest',
            name='origin',
        ),
        migrations.AddField(
            model_name='problemsrecommendation',
            name='origin',
            field=models.IntegerField(blank=True, choices=[(1, '提高'), (2, '补弱')], null=True, verbose_name='题目类型'),
        ),
    ]
