# Generated by Django 3.1.1 on 2022-06-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20220611_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '有效测验记录'), (2, '无效测验记录')], null=True, verbose_name='题目类型'),
        ),
    ]
