# Generated by Django 3.1.1 on 2022-06-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_testrecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='last_test_pass_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='上一次测验正确率'),
        ),
        migrations.AlterField(
            model_name='users2concepts',
            name='last_score',
            field=models.FloatField(blank=True, null=True, verbose_name='上一次掌握情况'),
        ),
    ]
