# Generated by Django 3.1.1 on 2022-07-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20220615_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstest',
            name='simulationNum',
            field=models.IntegerField(blank=True, choices=[(1, '模拟试卷1'), (2, '模拟试卷2'), (3, '模拟试卷3')], null=True, verbose_name='模拟试卷序号'),
        ),
        migrations.AddField(
            model_name='problemstest',
            name='testCategory',
            field=models.IntegerField(blank=True, choices=[(1, '普通测验'), (2, '模拟考试')], null=True, verbose_name='测验类型'),
        ),
    ]
