# Generated by Django 3.1.1 on 2022-07-18 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_auto_20220718_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareData',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('dataSimulationProbNid', models.TextField(blank=True, null=True, verbose_name='模拟测试的问题nid记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
