# Generated by Django 5.0.7 on 2024-07-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0019_sharedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingProblem",
            fields=[
                ("nid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="题目类别"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="题目编号"
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "简单"), (1, "中等"), (2, "提高")],
                        null=True,
                        verbose_name="题目难度",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="题目创建时间"),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="题目来源"
                    ),
                ),
                ("pass_count", models.IntegerField(default=0, verbose_name="题目通过次数")),
                ("submit_count", models.IntegerField(default=0, verbose_name="题目提交次数")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="题目标题"
                    ),
                ),
                (
                    "original_text",
                    models.TextField(blank=True, null=True, verbose_name="题目描述"),
                ),
                (
                    "equation",
                    models.TextField(blank=True, null=True, verbose_name="等式"),
                ),
                (
                    "segmented_text",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="语义题目"
                    ),
                ),
                (
                    "input",
                    models.TextField(blank=True, null=True, verbose_name="题目输入描述"),
                ),
                (
                    "output",
                    models.TextField(blank=True, null=True, verbose_name="题目输出描述"),
                ),
                (
                    "input_sample",
                    models.TextField(blank=True, null=True, verbose_name="题目输入样例"),
                ),
                (
                    "output_sample",
                    models.TextField(blank=True, null=True, verbose_name="题目输出样例"),
                ),
                (
                    "html_path",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="题目对应html路径"
                    ),
                ),
                (
                    "img_path",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="题目图片路径"
                    ),
                ),
            ],
        ),
    ]
