# Generated by Django 5.0.7 on 2024-07-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0020_programmingproblem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmingproblem",
            name="segmented_text",
            field=models.TextField(
                blank=True, max_length=128, null=True, verbose_name="语义题目"
            ),
        ),
    ]
