# Generated by Django 5.0.7 on 2024-07-31 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0022_problems_equation_problems_segmented_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProgrammingProblem",
        ),
    ]
