# Generated by Django 5.0.7 on 2024-07-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0023_delete_programmingproblem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProblemRecords",
        ),
    ]
