# Generated by Django 5.0.7 on 2024-07-31 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0024_delete_problemrecords"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemRecords",
            fields=[
                ("nid", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.FloatField(blank=True, null=True, verbose_name="得分")),
                (
                    "code_path",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="题目上传代码路径"
                    ),
                ),
                (
                    "prob_submit_count",
                    models.IntegerField(default=0, verbose_name="当前用户提交这道题目次数"),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="做题时间"),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.problems",
                        verbose_name="题号",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.testrecord",
                        verbose_name="测验表号",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="做题用户",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "做题记录",
            },
        ),
    ]
