# Generated by Django 5.0.7 on 2024-07-31 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0025_problemrecords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problems",
            name="equation",
        ),
    ]
