# Generated by Django 5.0.7 on 2024-07-31 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0026_remove_problems_equation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problems",
            name="segmented_text",
        ),
    ]
