# Generated by Django 5.0.7 on 2024-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0027_remove_problems_segmented_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="problems",
            name="equation",
            field=models.TextField(blank=True, null=True, verbose_name="等式"),
        ),
        migrations.AddField(
            model_name="problems",
            name="segmented_text",
            field=models.TextField(
                blank=True, max_length=128, null=True, verbose_name="语义题目"
            ),
        ),
    ]
